const CONFIG = {
  APPS_SCRIPT_URL: "https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec",
  SHEET_ID: "YOUR_GOOGLE_SHEET_ID",
  DRINKS: [
    { id: "b1", name: "Draft Beer",   price: 28, cat: "beer" },
    { id: "b2", name: "Bottle Beer",  price: 24, cat: "beer" },
    { id: "b3", name: "IPA",          price: 32, cat: "beer" },
    { id: "b4", name: "Guinness",     price: 30, cat: "beer" },
    { id: "s1", name: "Whiskey",      price: 38, cat: "spirits" },
    { id: "s2", name: "Vodka",        price: 35, cat: "spirits" },
    { id: "s3", name: "Tequila",      price: 38, cat: "spirits" },
    { id: "s4", name: "Rum",          price: 35, cat: "spirits" },
    { id: "s5", name: "Gin",          price: 38, cat: "spirits" },
    { id: "s6", name: "Arak",         price: 30, cat: "spirits" },
    { id: "w1", name: "House Wine",   price: 35, cat: "wine" },
    { id: "w2", name: "Red Wine",     price: 38, cat: "wine" },
    { id: "w3", name: "White Wine",   price: 38, cat: "wine" },
    { id: "w4", name: "Rosé",         price: 38, cat: "wine" },
    { id: "c1", name: "Mojito",       price: 55, cat: "cocktails" },
    { id: "c2", name: "Margarita",    price: 55, cat: "cocktails" },
    { id: "c3", name: "Negroni",      price: 58, cat: "cocktails" },
    { id: "c4", name: "G&T",          price: 42, cat: "cocktails" },
    { id: "c5", name: "Long Island",  price: 65, cat: "cocktails" },
    { id: "f1", name: "Soft Drink",   price: 15, cat: "soft" },
    { id: "f2", name: "Water",        price: 12, cat: "soft" },
    { id: "f3", name: "Coffee",       price: 18, cat: "soft" },
    { id: "f4", name: "Fresh Juice",  price: 20, cat: "soft" },
  ],
};
